params = {"N": 50,
            "S": 8531,
            "T": 6000,
            "K": 4,
            "f": 0.1,
            "stepK": 4,
            "stepP": 0.0,
            "binomial_p": 0.4,
            "gaussian_stdK": 1,
            "lognormal_stdK": 1,
            "reps": 3,
            "correlated": False,
            "corr_ell": 2}
